# Generated by Django 6.1.1 on 2026-09-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0002_alter_empleado_options'),
        ('ventas_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'verbose_name': 'Producto de la Venta', 'verbose_name_plural': 'Productos de la Venta'},
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='metodo_pago',
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas_productos.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas_productos.venta'),
            preserve_default=False,
        ),
    ]
