# Generated by Django 6.1.1 on 2026-09-15 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0002_alter_empleado_options'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planes.plan')),
            ],
            options={
                'verbose_name': 'Venta de Plan',
                'verbose_name_plural': 'Ventas de Planes',
            },
        ),
    ]
