# Generated by Django 6.1.1 on 2026-09-19 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaplan',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
