# Generated by Django 6.1.1 on 2026-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_planes', '0002_alter_ventaplan_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaplan',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
