# Generated by Django 6.1.1 on 2026-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_planes', '0003_ventaplan_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaplan',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
