# Generated by Django 6.1.1 on 2026-09-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_planes', '0004_alter_ventaplan_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaplan',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventaplan',
            name='monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ventaplan',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
