# Generated by Django 6.1.1 on 2026-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duracion_dias',
            new_name='duracion',
        ),
        migrations.AddField(
            model_name='plan',
            name='tipo_plan',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('promocion', 'Promoción')], default='estandar', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='unidad_duracion',
            field=models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses')], default='meses', max_length=10),
        ),
    ]
