# Generated by Django 6.1.1 on 2026-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_rename_duracion_dias_plan_duracion_plan_tipo_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fecha_fin_promocion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_inicio_promocion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
