# Generated by Django 6.1.1 on 2026-09-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_diarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiaria',
            name='tipo_entrada',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('promocion', 'Promoción')], default='estandar', max_length=20),
        ),
    ]
