# Generated by Django 6.1.1 on 2026-09-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_diarias', '0002_entradadiaria_tipo_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Entrada',
                'verbose_name_plural': 'Tipos de Entrada',
            },
        ),
        migrations.AlterField(
            model_name='entradadiaria',
            name='tipo_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entradas_diarias.tipoentrada'),
        ),
    ]
