# Generated by Django 6.1.1 on 2026-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_diarias', '0003_tipoentrada_alter_entradadiaria_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoentrada',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
