# Generated by Django 6.1.1 on 2026-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_diarias', '0004_tipoentrada_predeterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadiaria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
