# Generated by Django 6.1.1 on 2026-09-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas_diarias', '0005_alter_entradadiaria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadiaria',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entradadiaria',
            name='monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
